### ISSUE TITLE
Impute missing values of Y and Y_err based on given Y and Y_err values

### ISSUE THREAD

**Issue by darshanbeniwal78** [bflammers/ANN2#14]
Dear ANN2 developer.

I have around 30 datapoints of X, Y, and Y_err between x-range=[0,2.2]. Graphically, this dataset shows a monotonically increasing behavior with the x-axis. Without assuming any model or polynomial, I want to generate missing values of Y and Y_err based on the given dataset only between the same x-range. I mean I want to reconstruct this dataset of 30 data points with a data-driven approach only as shown in the attached file. I also attached the dataset.

[data.txt](https://github.com/bflammers/ANN2/files/4840067/data.txt)
![Reconstructed_Plot](https://user-images.githubusercontent.com/13278191/85916618-1bc58980-b870-11ea-8444-e41e7a68c7e0.jpg)

Could you please help me to handle this issue?

Thank you.

Sincerely.

**Comment by bflammers** [comment]
The functionality to impute missing values is not built into ANN2, but you can do it pretty easily using the autoencoder function. With the trained autoencoder, you assess the fit of each imputation candidate. The candidate with the highest fit is the winner. This basically is a grid search over a predefined set of values that you insert into the missing field, with the autoencoder as a fitness function. Take a look at the code below for an example. 

This is an example plot showing for each candidate (fixed known values for X and Yerr, grid of values between 50 and 200 for Y, since Y is the "missing" field to be imputed) the fitness. Reading this plot, given a value of X of 0.88 and a value for Yerr of 40, a value for Y around 125 seems to give the highest fit. Meaning that the imputation candidate of approximately c(0.88, 125, 40) is most consistent with the training data.
![image](https://user-images.githubusercontent.com/15668381/85918051-b10c5200-b85f-11ea-8957-f99c6b64965c.png)

This is an example plot showing the original value (in blue) and the imputed value (in red). This shows why autoencoders are suitable for anomaly detection: they can be used to "de-noise" datapoints, reconstructing them at the points most consistent with the rest of the data. Anomalies are in general not "close" to the rest of the data, so the reconstruction error becomes high. The procedure taken to get to this imputed value is not the same as used in anomaly detection, but the denoising property of autoencoders applies to both. 
![image](https://user-images.githubusercontent.com/15668381/85918060-c5e8e580-b85f-11ea-8b2b-1ba4a0e8493e.png)

```
library(ggplot2)
library(ANN2)

# Load data
data <- read.csv('./data/data.csv', header=TRUE, sep = "\t")

# Divide into training set and records to impute 
index <- 23
target <- data[index, ]
incomplete_record <- target
incomplete_record[, 2] <- NA
df <- data[setdiff(1:nrow(data), index), ]

# Plot training data
scatter <- ggplot(data=df, mapping = aes(x = X, y = Y, size=Yerr)) + 
  geom_point(data = target, colour='blue') +
  geom_point()

# Show plot
scatter

# Train autoencoder 
AE <- autoencoder(df, hidden.layers = c(5, 2, 5), optim.type = 'adam', 
                  batch.size = 8, n.epochs = 1e5, val.prop = 0)
plot(AE)

# Show original points and reconstructions
reconstruction_plot(AE, df)

# Function to create imputation candidates (grid)
create_candidates <- function(record, min_val, max_val, n=1000) {
  
  # Which should be imputed (field is missing)
  idx_missing <- which(is.na(record))
  
  # Create grid vector for each missing field
  grid_isolated <- replicate(length(idx_missing), 
                             seq(min_val, max_val, length.out = n), 
                             simplify = FALSE)
  
  # Combine grid cols into grid
  grid_cols <- expand.grid(grid_isolated)

  # Expand rows to match grid, put grid back in replicated record
  grid <- record[rep(1, nrow(grid_cols)),]
  grid[, idx_missing] <- grid_cols
  
  return( data.frame(grid) )
}

# Function to assess fit of each candidate
impute_AE <- function(object, record, candidates) {
  
  # Which should be imputed (field is missing)
  idx_missing <- which(is.na(record))
  
  # Assess fit of each candidate
  rec_object <- reconstruct(object, candidates)
  rec_candidates <- data.frame(rec_object$reconstructed)
  rec_anomaly_scores <- rec_object$anomaly_scores
  
  # Determine winner
  winner <- candidates[which.min(rec_anomaly_scores), ]
  
  return ( list(
    winner = winner, 
    candidates = candidates, 
    fit = 1-(rec_anomaly_scores / max(rec_anomaly_scores))
  ))
}

# Create imputation candidates on grid
candidates <- create_candidates(incomplete_record, 
                                min_val = 50, 
                                max_val = 200)

# Plot
scatter + geom_point(data = candidates)

# Assess fit of each candidate using the trained autoencoder
impute_object <- impute_AE(AE, incomplete_record, candidates)

# Plot all candidates along with fit
scatter + 
  geom_point(data = impute_object$candidates, 
             mapping = aes(x=X, y=Y, colour=impute_object$fit)) + 
  scale_colour_viridis_c()

# Plot winner (red) and original datapoint (blue)
scatter + 
  geom_point(data = impute_object$winner, colour='red')
  ```

**Comment by darshanbeniwal78** [comment]
Dear Bart Lammers

Thank you for your reply.

I got your idea regarding the same using autoencoder. But somehow this code is not executable in my system. R studio in my system doesn't show any plot. Could you please tell me what could be the reason. 

And also wanted to plot 1 sigma region with the predicted value of y from autoencoder. Could I get more info/code for this?

I highly appreciate for your help and for providing ANN2.

Sincerely
